---
version: 0.2

phases:
  install:
    commands:
      - pip install awscli

  pre_build:
    commands:
      - OUTPUT_DATE="$(date +'%Y/%m/%d/%H/%M')"

  build:
    commands:
      - ./main.sh

  post_build:
    commands:
      - echo "Done!"
